languageName: "ä¸­æ–‡ğŸ‡¨ğŸ‡³"
contentDir: content/zh
languageCode: zh-CN
weight: 2
params:
  # homeInfoParams:
  #   Title: "\U0001F44B æ¬¢è¿æ¥åˆ°QÃ­çš„åšå®¢"
  #   Content: Hi, this is QÃ­, a student . 
  profileMode:
    enabled: true
    title: "\U0001F44B æ¬¢è¿å…‰ä¸´Qiçš„åšå®¢"
    subtitle:  "ğŸŒŸæˆä¸ºä¸€ä¸ªæœ‰è¶£çš„äººğŸŒŸ"
    imageUrl: "/img/logo-512.gif"
    imageTitle: Selfie
    imageWidth: 150
    imageHeight: 150
    buttons:
      - name: ğŸŒˆå…³äº
        url: about
      - name: ğŸ“šæ–‡ç« 
        url: posts
      - name: ğŸ™‹ğŸ»â€â™‚ï¸ç®€å†
        url: about/resume.pdf

menu:
  main:
    # - identifier: About
    #   name: ğŸŒˆå…³äº
    #   url: about
    #   weight: 1
    - identifier: Blog
      name: ğŸ“šæ–‡ç« 
      url: posts
      weight: 2
    - identifier: Archives
      name: â±ï¸æ—¶é—´è½´
      url: archives
      weight: 3
    - identifier: Tags
      name: ğŸ”–æ ‡ç­¾
      url: tags
      weight: 4
    - identifier: Categories
      name: ğŸ§©ç±»ç›®
      url: categories
      weight: 5
    - identifier: Search
      name: ğŸ”æœç´¢
      url: search
      weight: 6