languageName: "EnglishğŸ‡ºğŸ‡¸"
contentDir: content/en
languageCode: en-US
weight: 1
params:
  # homeInfoParams:
  #   Title: "\U0001F44B Welcome to QÃ­ Blog"
  #   Content: Hi, this is QÃ­, a student . 
  profileMode:
    enabled: true
    title: "\U0001F44B Welcome to QiBlog"
    subtitle: "ğŸŒŸBe InterestingğŸŒŸ"
    # imageUrl: "Avatar.png"
    imageUrl: "/img/logo-512.gif"
    imageTitle: Selfie
    imageWidth: 150
    imageHeight: 150
    buttons:
      - name: ğŸŒˆAbout
        url: about
      - name: ğŸ“šBlog
        url: posts
      - name: ğŸ™‹ğŸ»â€â™‚ï¸Resume
        url: about/resume.pdf

menu:
  main:
    # - identifier: About
    #   name: ğŸŒˆAbout
    #   url: about
    #   weight: 1
    - identifier: Blog
      name: ğŸ“šBlogs
      url: posts
      weight: 2
    - identifier: Archives
      name: â±ï¸Archives
      url: archives
      weight: 3
    - identifier: Tags
      name: ğŸ”–Tags
      url: tags
      weight: 4
    - identifier: Categories
      name: ğŸ§©Categories
      url: categories
      weight: 5
    - identifier: Search
      name: ğŸ”Search
      url: search
      weight: 6